--- # my playbook for variable
- hosts: prod
  user: ansible
  become: yes
  connection: ssh
  tasks:
        - name: install HTTPD server on redhat 9
          action: yum name=httpd state=installed
          notify: restart httpd
  handlers: 
          - name: restart httpd
            action: service name=httpd state=restarted
