--- # my loop
- hosts: prod
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: add list of users in my nodes
      user: name='{{item}}' state=present
      with_items:
        - abc
        - bcd
        - cde
        - def
